### ISSUE TITLE
Setting for which days are allowed to be changed does not work properly.

### ISSUE THREAD

**Issue by rozie** [lordi/tickmate#111]
When I have selected "active day and day before" I can edit only current day.
When I have selected "active day only" I couldn't edit anything. 31.05.2017, Wednesday, if that matters.

**Comment by rozie** [comment]
Today morning is worked as expected (at least worked "the day before"). At 7PM can't change the day before.

**Comment by lordi** [comment]
Interesting, will investigate

**Comment by rozie** [comment]
Made some tests and look that it switches exactly at noon. Iteresting, as I have 24 hour time set in device and it's automatically synchronized.

**Comment by StefRe** [comment]
Although I didn't have the time to reproduce the error, I'm pretty sure that my PR #112 should resolve this issue (ButtonHelpers.java line 22)

**Comment by lordi** [comment]
I'll close this. Please re-open if #112 does not fix your issue.
